version: '3.9'
services:
#node application container
#env vars already set in built time
  node-app:
    restart: always
    image: "${pvtimg}"
    ports:
      - 3000:3000

#mongod container 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${admin}
      - MONGO_INITDB_ROOT_PASSWORD=${password}
    volumes:
      - mdbspace:/data/db

#mongo-express container
  mdbxpress:
    image: mongo-express
    restart: always #restarts if unable to connect to unfinished mdb container
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${password}
      - ME_CONFIG_MONGODB_SERVER=mongodb

#volume created locally
volumes:
  mdbspace:
    driver: local

#a common network will be created automatically
#and joined as well

#first start mdb , then express and then node
